# [[block]]
# block = "bluetooth"
# mac = "DC:0D:11:A1:6A:99"
# format = "Corne {percentage}"
#
# [[block]]
# block = "bluetooth"
# mac = "4C:87:5D:7D:D5:C4"
# format = "Nightshade"

[[block]]
block = "time"
interval = 20
format = "%a %d/%m %R"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
icons_format = "{icon}"
format = "{utilization:3} {barchart}"

# [[block]]
# block = "net"
# device = "wlan0"
# format = "{ssid} {signal_strength}"
# interval = 5
# hide_inactive = true
# hide_missing = true

[[block]]
block = "networkmanager"
on_click = "kitty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^10}"

[[block]]
block = "backlight"

[[block]]
block = "sound"
driver = "pulseaudio"
natural_mapping = true
show_volume_when_muted = true
on_click = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "sound"
driver = "pulseaudio"
natural_mapping = true
show_volume_when_muted = true
on_click = "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
device_kind = "source"

# [[block]]
# block = "battery"
# interval = 20
# allow_missing = true
# hide_missing = true
# format = "{percentage} {time}"

[theme]
name = "nord-dark"

[theme.overrides]
# alternating_tint_bg
# alternating_tint_fg
idle_bg = "#282c34" 
idle_fg = "#c8ccd4" 
info_bg = "#56b6c2" 
info_fg = "#282c34" 
good_bg = "#98c379" 
good_fg = "#282c34" 
warning_bg = "#d19a66" 
warning_fg = "#282c34" 
critical_bg = "#e06c75" 
critical_fg = "#282c34" 
# separator_bg
# separator_fg
# separator

[icons]
name = "material-nf"

# set $base00 #282c34
# set $base01 #353b45
# set $base02 #3e4451
# set $base03 #545862
# set $base04 #565c64
# set $base05 #abb2bf
# set $base06 #b6bdca
# set $base07 #c8ccd4
# set $base08 #e06c75
# set $base09 #d19a66
# set $base0A #e5c07b
# set $base0B #98c379
# set $base0C #56b6c2
# set $base0D #61afef
# set $base0E #c678dd
# set $base0F #be5046

