# [[block]]
# block = "bluetooth"
# mac = "4C:87:5D:7D:D5:C4"
# format = "Nightshade"
#
invert_scrolling = true
[[block]]
block = "net"
format = " $icon {$ssid[$signal_strength:$frequency]|Wired} "
interval = 10
[[block.click]]
button = "left"
cmd = 'wezterm start --class "nmtui" nmtui'

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "

[[block]]
block = "backlight"

[[block]]
block = "sound"
driver = "pulseaudio"
headphones_indicator =  true
natural_mapping = true
show_volume_when_muted = true

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
show_volume_when_muted = true

[[block]]
block = "time"
interval = 20

[[block]]
block = "battery"
# if_command = "cat /sys/class/power_supply/BAT1/capacity"
interval = 20
missing_format = ""
format = " $icon $percentage {$time |}"

# [[block]]
# block = "menu"
# text = " \uf011 "
# [[block.items]]
# display = " -&gt;   Sleep   &lt;-"
# cmd = "systemctl suspend"
# [[block.items]]
# display = " -&gt; Power Off &lt;-"
# cmd = "poweroff"
# confirm_msg = "Are you sure you want to power off?"
# [[block.items]]
# display = " -&gt;  Reboot   &lt;-"
# cmd = "reboot"
# confirm_msg = "Are you sure you want to reboot?"


[theme]
theme = "nord-dark"
[theme.overrides]
alternating_tint_bg = "#282c34"
idle_bg = "#282c34"
idle_fg = "#c8ccd4"
info_bg = "#61afef"
info_fg = "#282c34"
good_bg = "#98c379"
good_fg = "#282c34"
warning_bg = "#e5c07b"
warning_fg = "#282c34"
critical_bg = "#e06c75"
critical_fg = "#282c34"
# separator_bg
# separator_fg
# separator

[icons]
icons = "material-nf"

# set $base00 #282c34
# set $base01 #353b45
# set $base02 #3e4451
# set $base03 #545862
# set $base04 #565c64
# set $base05 #abb2bf
# set $base06 #b6bdca
# set $base07 #c8ccd4
# set $base08 #e06c75
# set $base09 #d19a66
# set $base0A #e5c07b
# set $base0B #98c379
# set $base0C #56b6c2
# set $base0D #61afef
# set $base0E #c678dd
# set $base0F #be5046
