#!/bin/bash
# updots

[ ! $YADM_HOOK_EXIT -eq 0 ] && exit $YADM_HOOK_EXIT;

CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME}/yadm/pkgs
DEFAULT_PKGS=$CONFIG_DIR/default.pkgs
FOREIGN_PKGS=$CONFIG_DIR/foreign.pkgs

mkdir -pv $CONFIG_DIR
touch $DEFAULT_PKGS
touch $FOREIGN_PKGS

# Do an update
paru -Syu

# Install Any PKGs needed but not ignored from .pkgs
paru -Qqe |
  sort |
  comm -23 <(sort $CONFIG_DIR/*.pkgs) - |
  comm -12 <(sort $DEFAULT_PKGS) - |
  paru -S - --needed

# # Install Any Foreign PKGs needed but not ignored from .pkgs
paru -Qqe |
  sort |
  comm -23 <(sort $CONFIG_DIR/*.pkgs) - |
  comm -12 <(sort $FOREIGN_PKGS) - |
  paru -S - --needed

if [[ -e $1 ]]; then
  paru -Qqe |
    sort |
    comm -23 <(sort $CONFIG_DIR/*.pkgs) - |
    comm -12 <(sort $1) - |
    paru -S - --needed
fi


# Regenerate .pkgs ignoring ignored pkgs
comm -23 <(sort $CONFIG_DIR/*.pkgs) <(sort $DEFAULT_PKGS) |
  comm -23 <(paru -Qqen | sort) - > $DEFAULT_PKGS

comm -23 <(sort $CONFIG_DIR/*.pkgs) <(sort $FOREIGN_PKGS) |
  comm -23 <(paru -Qqem | sort) - > $FOREIGN_PKGS

# Check for pacnew/saves
DIFFPROG='nvim -d' pacdiff -s

